#
###################################
# Site wide configuration
####################################
#
title: Love Steak
email: lavelee15@gmail.com
description: A dev blog
url: https://lavelee.github.io/blog/
keywords: ["blog", "developer"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          Asia/Seoul
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: SungHyun Lee
  avatar: me.jpeg
  job: "Software Engineer"
  bio: "주로 웹 프론트/백엔드를 개발합니다"
  email: lavelee15@gmail.com
  disqus-shortname: lavelee
  twitter: #username
  facebook: #username
  google:
    plus: #username
    analytics: UA-90005131-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: lavelee
  gitlab: #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: sunghyun-lee-1654ba194
  skype: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  500px: #username
  codepen: #username
  reddit: #username
  telegram: #username
